app/main/forms.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_pagedown.fields import PageDownField


class LoginForm(FlaskForm):
    username = StringField('Username:', validators=[DataRequired()])
    password = PasswordField('Password:', validators=[DataRequired(), Length(min=6,max=18)])
    login = SubmitField('Login')
    logout = SubmitField('Logout')


class PostForm(FlaskForm):
    body = PageDownField("博客内容:", validators=[DataRequired()])
    submit = SubmitField("发布")

app/__init__.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from flask import Flask
from flask_mail import Mail
from flask_login import LoginManager
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_pagedown import PageDown
from flask_bootstrap import Bootstrap
from config import config

db = SQLAlchemy()
mail = Mail()
moment = Moment()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
pagedown = PageDown()
bootstrap = Bootstrap()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)
    bootstrap.init_app(app)

    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from app.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from app.admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from app.api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix="/api/v1.0")

    return app

app/admin/__init__.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from flask import Blueprint
admin = Blueprint('admin', __name__)

import app.admin.views

app/admin/views.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from flask import render_template
from . import admin


@admin.route('/')
def admin_index():
    return render_template('admin/base.html')

app/api_1_0/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# @Time    : 2017-10-08 22:50
# @Author  : 钟伟 <zhong.wei@qq.com>
#

from flask import Blueprint

api = Blueprint('api', __name__)

from . import users, authentication, errors, posts

app/main/__init__.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from flask import Blueprint
main = Blueprint('main', __name__)


from . import views, forms
from app.model import Permission


@main.app_context_processor
def inject_permission():
    return dict(Permission=Permission)

app/main/views.py
# _*_ coding: utf-8 _*_
#
# Copyright (C) 2017 钟伟 <zhong.wei@qq.com>
# All rights reserved.
#
# Author: 钟伟 <zhong.wei@qq.com>
#

from .forms import PostForm, LoginForm
from flask import render_template, abort, redirect, url_for, session, flash
from app.main import main
from app.model import User, Post
from flask_login import current_user
from app import db


@main.route('/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        pass


@main.route('/', methods=['GET'])
def index():
    form = PostForm()
    author = current_user._get_current_object()
    if form.validate_on_submit():
        body = form.body.data
        post = Post(body=body, author_id=author.id)
        db.session.add(post)
        return redirect(url_for('main.index'))
    posts = Post.query.order_by(Post.create_date.desc()).all()
    return render_template("index.html", form=form, posts=posts)


@main.route('/user/<user_id>')
def user(user_id):
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('user.html', user=user)


@main.route('/post/<id>')
def post(id):
    post = Post.query.get_or_404(id)
    user = User.query.get_or_404(post.author_id)
    return render_template('post.html', post=post, author=user)


@main.errorhandler(404)
def page_not_found(e):
    abort(404)
    return render_template("404.html"), 404

app/templates/_posts.html
{% extends "base.html" %}
{% block title %} 首页 {% endblock %}

{% block blog_main %}
<div class="container">
    {% if post.body_html %}
    {{ post.body_html | safe }}
    {% else %}
    {{ post.body }}
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<!--moment插件引用的JS-->
{{ moment.include_jquery() }}
{{ moment.include_moment() }}
{{ moment.lang("zh-CN") }}
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}zhongwei.me{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">ZhongWei</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang("zh-CN") }}
{% endblock %}

app/templates/hello.html
{% extends "header.html" %}
{% block title %}
My Site
{% endblock %}

{% block content %}
{% if name %}
<h1>Hello {{ name }}</h1>
{% else %}
<h1> Hello Stranger</h1>
{% endif %}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username() }}
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %} 首页 {% endblock %}

{% block page_content %}
<div class="form-group">
    {% if current_user.can(Permission.WRITE_ARTICLE) %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.body(placeholder="写点什么...", class="form-control", rows="4") }} <br>
        {{ form.submit(class="btn btn-outline-success float-right") }}
    </form>
    {% endif %}
</div>
<div>
    <ul>
        {% for post in posts %}
        <li style="list-style-type: none">
            <div class="row">
                <div class="col-md-7">
                    <a href="{{ url_for('main.user', user_id=post.author.id) }}">{% if post.author.display_name %}
                        {{ post.author.display_name }}
                        {% else %}
                        {{ post.author.email }}
                        {% endif %}</a>
                </div>
                <div class="col-md-5">
                    {{ moment(post.create_date).fromNow() }}
                </div>
            </div>
            <div>
                {{ post.body_html | safe}}
            </div>
        </li>

        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<!--moment插件引用的JS-->

<!--pagedown插件引用的JS-->
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% block title %} 首页 {% endblock %}

{% block blog_main %}
<div class="container">
    {{ post.body_html | safe }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<!--moment插件引用的JS-->
{{ moment.include_jquery() }}
{{ moment.include_moment() }}
{{ moment.lang("zh-CN") }}
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>
    {% if user.display_name %}
        {{ user.display_name }}
    {% else %}
        {{ user.email }}
    {% endif %}
</h1>
<p>
    Member Since: {{ moment(user.member_since).format('L') }} <br>
    最后活动时间: {{ moment(user.last_seen).fromNow() }}
</p>
{% endblock %}